### ISSUE TITLE
Custom arkOS nginx.conf / Subdomains fail when new network IP address assigned

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#402] opened 2014-07-11 08:37 UTC
So, I set up about 6 plugins: XMPP, Mumble, Mail, Wordpress, Ghost and ownCloud.

They all seem to go through the setup process ok, but the Ghost / WordPress / ownCloud sites, when I click on them, or when I visit their URL's FireFox just reports the following error message:

"Server not found
Firefox can't find the server at www.owncloud.arkos.
Check the address for typing errors such as ww.example.com instead of www.example.com"

The arkOS interface though works fine on arkos:8000

No errors show in the log or in the console. This may be related to #401 but I'm not sure.

**Comment by peakwinter** [comment] 2015-04-13 22:42
Upon closer reading this looks like a duplicate of #424. Please let me know if this is not the case.

**Closed by peakwinter** 2015-04-13 22:42 UTC

**Comment by Bugsbane** [comment] 2015-04-15 17:44
Yeah, looks like it is, although I didn't know it when I filed.
