### ISSUE TITLE
Error page when trying to update Genesis (current version 0.6.0)

### ISSUE THREAD

**Issue by CubieTruck-ArkOS-OwnCloud** [cznweb/genesis#499] opened 2015-01-17 12:08 UTC
Hi all,

When trying to update Genesis, as suggested by a Big Blue Button, instead of updating, it sends me to an error-page;

"Sorry, an error has occurred.
Genesis encountered an error when trying to perform your last requested operation, and it cannot continue it. "

I've tried again a couple of times, also after reloading Genesis and even a full reboot. Nothing changes.

Genesis 0.6.0 bug report
--------------------

System: Linux [myhostname] 3.4.79-8-ARCH #1 SMP PREEMPT Tue May 6 11:17:54 MDT 2014 armv7l GNU/Linux

Detected platform: arkos
Detected distro: Linux 3.4.79-8-ARCH armv7l

Python: 2.7.8

Config path: /etc/genesis/users/root.conf

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/genesis/core/application.py", line 166, in dispatcher
    self.start_response)
  File "/usr/lib/python2.7/site-packages/genesis/api/urlhandler.py", line 89, in url_handler
    return handler(req, start_response)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/core/root.py", line 282, in handle_generic
    result = handler.event(event, params, vars = vars)
  File "/usr/lib/python2.7/site-packages/genesis/api/helpers.py", line 115, in event
    return handler(event, *params, **kwparams)
  File "/usr/lib/python2.7/site-packages/genesis/plugins/config/main.py", line 115, in on_submit
    shell('pacman -S --noconfirm genesis')
NameError: global name 'shell' is not defined

Loaded plugins:
db-mariadb
owncloud
php
samba
ssh

Log:
(Showing only the last 50 entries)

2015-01-17 12:50:16,883 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:16,977 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:19,204 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:19,252 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:19,280 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:19,369 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:21,419 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:21,465 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:21,488 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:21,572 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:23,672 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:23,713 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:23,733 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:23,818 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:25,874 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:25,915 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:25,939 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:26,023 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:28,079 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:28,119 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:28,147 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:28,241 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:30,285 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:30,326 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:30,353 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:30,438 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:32,479 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:32,520 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:32,550 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:32,633 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:34,670 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:34,712 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:34,738 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:34,822 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:36,866 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:36,906 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:36,932 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:37,016 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:37,830 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-01-17 12:50:37,871 [DEBUG] application: Dispatching /handle/button/click/updaction
2015-01-17 12:50:37,895 [DEBUG] application: Calling handler for /handle/button/click/updaction
2015-01-17 12:50:38,059 [DEBUG] application: Finishing /handle/button/click/updaction
2015-01-17 12:50:39,097 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:39,143 [DEBUG] application: Dispatching /core/progress
2015-01-17 12:50:39,170 [DEBUG] application: Calling handler for /core/progress
2015-01-17 12:50:39,253 [DEBUG] application: Finishing /core/progress
2015-01-17 12:50:40,160 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-01-17 12:50:40,201 [DEBUG] application: Dispatching /handle/dialog/submit/dlgUpdate
2015-01-17 12:50:40,226 [DEBUG] application: Calling handler for /handle/dialog/submit/dlgUpdate

**Comment by peakwinter** [comment] 2015-01-17 15:44
Hi there -- This issue has been solved for the next version; if it is affecting you in 0.6 you'll have to update Genesis manually, either through the Packages pane, or from the command line with sudo pacman -Sy genesis

Thanks!

(duplicate of #469)

**Closed by peakwinter** 2015-01-17 15:44 UTC

**Comment by CubieTruck-ArkOS-OwnCloud** [comment] 2015-01-17 17:35
This worked for me. Thank you!
